Fix examples error
pytest-dev/pytest-bdd pull request #391
Opened 2020-09-19 10:46 UTC by hicksjduk

2020-09-21 08:50 UTC, hicksjduk commented
@youtux, it seems that you were the last person to touch this code. Would you be able to review this PR, or else how do I request a review given that I don't have write access to the repo?

2021-02-10 10:30 UTC, elchupanebrej commented
@hicksjduk Could you please rename the pull request to something like "Allow store values in Examples not used in steps" to show the real value of this feature

@youtux Please review

2021-02-10 10:56 UTC, hicksjduk commented
Done.

2021-06-27 09:29 UTC, youtux requested changes

2021-06-27 09:29 UTC, youtux commented on pytest_bdd/parser.py
> +        if params and example_params and any(p not in example_params for p in params):
can we use set.issubset instead?

2021-06-28 10:48 UTC, hicksjduk commented on pytest_bdd/parser.py
> +        if params and example_params and any(p not in example_params for p in params):
Yes, of course. Change made.

2021-08-09 16:49 UTC, olegpidsadnyi reviewed
Cucumber (gherkin lint) uses no-unused-variables rule to optionally raise on this. @youtux Do you think we need to make it an option?

2021-08-10 08:25 UTC, hicksjduk commented
> 
> 
> Cucumber (gherkin lint) uses no-unused-variables rule to optionally raise on this. @youtux Do you think we need to make it an option?

Isn't this a rule in the linter that checks the implementation code? Not in the functionality that implements the gherkin bindings. I can't find any reference in the cucumber documentation to this rule.

2021-08-10 17:46 UTC, elchupanebrej commented
@hicksjduk Oleg means https://www.npmjs.com/package/gherkin-lint 
@olegpidsadnyi @hicksjduk please check #439 . User could explicitly decide to use this feature using new parameters in "scenario" and "scenarios"

2021-10-01 17:38 UTC, youtux commented
I think we should just allow examples to include values that are not used. I wouldn't make it an option, I find it unnecessary complication.

2021-10-01 18:03 UTC, youtux commented
@olegpidsadnyi please review

2024-10-05 09:43 UTC, jsa34 commented
@youtux  I don' think this restriction exists in the code base any more, from what I can see?

I can also see there is a test: _test_unused_params_ - is this covered by this test?

2024-10-06 16:04 UTC, youtux commented
yes exactly this can be closed indeed

2024-10-06 16:04 UTC, closed without merging