Implement localisation support
pytest-dev/pytest-bdd pull request #725
Opened 2024-10-19 19:41 UTC by youtux

Fixes https://github.com/pytest-dev/pytest-bdd/issues/397

2024-10-19 19:42 UTC, youtux commented
@jsa34 mind reviewing this too?

2024-10-20 08:41 UTC, jsa34 commented
There are some places where keywords are hardcoded, but I needed to resolve these for the rules PR, so this should fix this issue so that the gherkin terminal reporter and cucumber json out is using the desired keywords from the feature file, rather than assuming

2024-10-20 08:47 UTC, jsa34 commented
We should include the language in the cucumber json output.

https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/minimal/minimal.feature
https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/minimal/minimal.feature.ndjson

This is example of a minimal out that is cucumber-spec-compliant, and as no language is specified, it defaults to "en" in this example, but obviously we should pass the value coming from the gherkin parser.

2024-10-20 08:50 UTC, jsa34 requested changes
See comments in the MR

2024-10-20 09:46 UTC, jsa34 commented
Also resolves #179

2024-10-20 10:15 UTC, jsa34 commented
I also forgot an example and change log entry: it would be helpful to demonstrate how to specify the language in the feature file

2024-10-20 14:12 UTC, jsa34 commented on src/pytest_bdd/types.py
There is another type to map: Conjunction (And, But and *)

2024-10-24 16:44 UTC, youtux commented on src/pytest_bdd/types.py
I know, but that's just a "tokenizer" type, not a semantic one, that's why I didn't include it here

2024-10-24 16:50 UTC, youtux commented
> We should include the language in the cucumber json output.
> 
> https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/minimal/minimal.feature https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/minimal/minimal.feature.ndjson
> 
> This is example of a minimal out that is cucumber-spec-compliant, and as no language is specified, it defaults to "en" in this example, but obviously we should pass the value coming from the gherkin parser.

Do you know if there is a specification somewhere for Cucumber JSON output?

2024-10-24 17:04 UTC, youtux commented
> I also forgot an example and change log entry: it would be helpful to demonstrate how to specify the language in the feature file

yes I forgot indeed, added in 342cf5edcfb516d4a4136ff6b7e722e7e48590b7

2024-10-24 17:20 UTC, jsa34 commented
I think the parser test needs simplifying otherwise it will be a maintenance nightmare.
Perhaps just fix for this and then I will raise a PR to make the test more focussed.

2024-10-25 19:16 UTC, youtux commented
> I think the parser test needs simplifying otherwise it will be a maintenance nightmare. Perhaps just fix for this and then I will raise a PR to make the test more focussed.

Agree, but I think that once gherkin-official v30.0.0 is released, we can remove most of the classes in `gherkin_parser.py`, so let's wait for that one.

Can you check this again?

2024-10-25 20:24 UTC, jsa34 approved these changes

2024-10-25 20:24 UTC, merged

2024-10-25 20:24 UTC, jsa34 commented
All good to me now :)