fix: defalut value not covered by parameters passed through feature file
pytest-dev/pytest-bdd pull request #737
Opened 2024-11-08 08:41 UTC by yunxuo

**Describe the bug**
when given multi description for step as below code

```
@given('a user with username')
@given(parsers.parse('a user with username {username}'))
@given(parsers.parse('a user with username {username} and password {password}'))
def create_user(user, username="defaultuser", password='defaultpassword'):
    user['username'] = username
    user['password'] = password
```
and pass parameters from feature file in Scenario Outline
```  
Scenario Outline: User login
    Given a user with username <username> and password <password>
    When the user logs in with username <username> and password <password>
    Then the login should be <result>

    Examples:
      | username | password    | result  |
      | testuser | password123 | success |
```
Parameters username, password parameters passed through feature file cannot take effect.
The default values in def are always used。

see also:
https://github.com/pytest-dev/pytest-bdd/pull/610 pr fix this problems
https://github.com/pytest-dev/pytest-bdd/issues/512

2024-11-13 22:11 UTC, jsa34 commented
@yunxuo Can we add a test for this?

2024-11-13 22:12 UTC, jsa34 requested changes
Can we add a test for this?

2024-11-14 06:20 UTC, yunxuo commented
> Thanks for the PR! Can we add a test for this?

yes!

2024-11-15 03:54 UTC, jsa34 requested changes
I cannot see any changes?  I was expecting the tests to be added

2024-11-15 07:55 UTC, yunxuo commented
> I cannot see any changes? I was expecting the tests to be added

sorry I'm late.
I have pushed a test case in commit, but I don't know if it meets the repository specifications.

2024-11-15 09:23 UTC, jsa34 requested changes
I tried locally, and noticed tests fail - there seems to be issues with some step args now.

Could you address these test failures?

It appears to be when the kwarg needs to exist but isn't an arg of the step

2024-11-15 10:18 UTC, jsa34 commented
No, on the existing test.

I will invoke a run to report the tests that fail

2024-11-15 10:25 UTC, jsa34 commented
See failing tests:

https://github.com/pytest-dev/pytest-bdd/actions/runs/11854436082/job/33036622290?pr=737

2024-11-18 03:14 UTC, yunxuo commented
> I took a look quickly to see if I could find a way to fix this and maintain the cases I mentioned, and came up with something like:
> 
> ```
> def _execute_step_function(
>     request: FixtureRequest, scenario: Scenario, step: Step, context: StepFunctionContext
> ) -> None:
>     """Execute step function."""
>     __tracebackhide__ = True
> 
>     func_sig = signature(context.step_func)
>     converters = context.converters
> 
>     def _get_parsed_arguments():
>         """Parse and convert step arguments."""
>         parsed_args = context.parser.parse_arguments(step.name)
>         if parsed_args is None:
>             raise ValueError(
>                 f"Unexpected `NoneType` returned from parse_arguments(...) in parser: {context.parser!r}"
>             )
>         kwargs = {}
>         for arg, value in parsed_args.items():
>             param = func_sig.parameters.get(arg)
>             if param:
>                 if arg in converters:
>                     value = converters[arg](value)
>                 kwargs[arg] = value
>         return kwargs
> 
>     def _get_argument_values(kwargs):
>         """Get default values or request fixture values for missing arguments."""
>         for arg in get_args(context.step_func):
>             if arg not in kwargs:
>                 param = func_sig.parameters.get(arg)
>                 if param:
>                     if param.default != param.empty:
>                         kwargs[arg] = param.default
>                     else:
>                         kwargs[arg] = request.getfixturevalue(arg)
>         return kwargs
> 
>     kw = {
>         "request": request,
>         "feature": scenario.feature,
>         "scenario": scenario,
>         "step": step,
>         "step_func": context.step_func,
>         "step_func_args": {},
>     }
> 
>     request.config.hook.pytest_bdd_before_step(**kw)
> 
>     try:
>         # Use internal methods without passing redundant arguments
>         kwargs = _get_parsed_arguments()
> 
>         if "datatable" in func_sig.parameters and step.datatable is not None:
>             kwargs["datatable"] = step.datatable.raw()
>         if "docstring" in func_sig.parameters and step.docstring is not None:
>             kwargs["docstring"] = step.docstring
> 
>         kwargs = _get_argument_values(kwargs)
> 
>         kw["step_func_args"] = kwargs
> 
>         request.config.hook.pytest_bdd_before_step_call(**kw)
> 
>         return_value = call_fixture_func(fixturefunc=context.step_func, request=request, kwargs=kwargs)
> 
>     except Exception as exception:
>         request.config.hook.pytest_bdd_step_error(exception=exception, **kw)
>         raise
> 
>     if context.target_fixture is not None:
>         inject_fixture(request, context.target_fixture, return_value)
> 
>     request.config.hook.pytest_bdd_after_step(**kw)
> ```
> 
> If this helps :)

Great code! it's worked in my case.
u can changed this pr

2024-11-19 18:55 UTC, jsa34 commented
@youtux are you happy with the codecov?  If so, can we merge?

2024-11-22 05:53 UTC, jsa34 approved these changes

2024-12-01 09:07 UTC, youtux commented on src/pytest_bdd/scenario.py
> +                        kwargs[arg] = param.default
this is indeed unreachable code

2024-12-01 09:54 UTC, youtux commented on src/pytest_bdd/scenario.py
> +        kwargs = {k: v for k, v in parsed_args.items() if k in func_sig.parameters}
is this filtering required? can't we use `kwargs = parsed_args`?

2024-12-01 10:01 UTC, youtux commented
Thank you for your contribution @yunxuo. I took the liberty of applying fixes as I saw fit. 

@jsa34 can you review again please?

2024-12-01 10:45 UTC, jsa34 commented
Looks good to me - thanks for revisiting it for us :)

2024-12-01 10:46 UTC, jsa34 approved these changes

2024-12-01 10:50 UTC, merged